---
- name: Install docker prereqs
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop: "{{ docker_prereqs_pkgs }}"

- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install docker
  shell:
    cmd: curl -fsSL https://get.docker.com/ | sh
